### ISSUE TITLE
Foreign key constraint error on exportdesktophtml

### ISSUE THREAD

**Issue by bepaald** [bepaald/signalbackup-tools#270]
hi, 
I have been using this tool for a few days now and found it to be very, very helpful, thanks! It worked very well for me with different backups. 
Now: Only after reading issue #267 I understood that I can create an HTML-export directly from Signal Desktop. I tried that on Windows but received an error about "Foreign key constraint violated." I am hoping that this issue here might be the correct place to let you know...?

I tried the following:
```powershell
PS C:\aa\backup> .\signalbackup-tools_win --exportdesktophtml archive
 *** Starting log: 2025-01-11 16:27:06 ***
signalbackup-tools (C:\aa\backup\signalbackup-tools_win.exe) source version 20250107.092817 (Win) (SQlite: 3.47.2, OpenSSL: OpenSSL 3.4.0 22 Oct 2024)
``` 
[approx 1500 lines removed]
```powershell
[Warning]: Profile data empty. Not updating group recipient.
[Warning]: Failed to update profile data.
Importing installed stickerpacks
updateThreadsEntries
  Dealing with thread id: 1, 2, 3, 4, 18, 66, 38, 44, 29, 5, 6, 7, 8, 9, 10, 11, 12, 13, 50, 35, 14, 15, 16, 17, 19, 60, 54, 48, 45, 20, 21, 22, 23, 24, 25, 26, 27, 28, 30, 31, 32, 47, 79, 33, 34, 36, 37, 39, 40, 67, 52, 41, 42, 70, 49, 58, 82, 80, 63, 84, 98, 43, 46, 51, 53, 55, 56, 57, 59, 61, 68, 64, 62, 65, 69, 71, 72, 73, 74, 75, 76, 77, 78, 81, 83, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 99, 100, 101, 102, 103
Checking foreign key constraints...
[Error]: Foreign key constraint violated. This will not end well, aborting.

Please report this error to the program author.
------------------------------
| table   | parent    | fkid |
------------------------------
| message | recipient | 3    |
------------------------------
PS C:\aa\backup>
``` 

If you are interested in this problem, please let me know how to proceed 
Cheers!

_Originally posted by @lesslame in https://github.com/bepaald/signalbackup-tools/issues/250#issuecomment-2585324838_

**Comment by bepaald** [comment]
@lesslame Thank you for reporting, this definitely looks like a bug in this program.

>If you are interested in this problem, please let me know how to proceed

I am very interested. I need to think a bit about where this issue could arise, or how to print relevant info. I'll have some instructions for you when I think of something. I might even build a custom version of the tool which provides more useful output, if you're willing to help track this down. Those 1500 lines removed might also contain useful information, but I'll let you know if I think that is likely.

Hopefully I have some time for investigating tomorrow. Thanks again!

**Comment by lesslame** [comment]
Hi, 
thanks for your quick answer. I would be happy to support your work!
Let me know what to do once you are ready.
Cheers!

**Comment by bepaald** [comment]
Since I hadn't had any reports like this one before, I started out just looking at my last commits to the `exportdesktophtml` code. I did actually find an issue in there with which I could reproduce your results (though I had to specially craft a desktop-database to run into it).

I think I have just fixed that problem, and hopefully that was it. So, please just update, and try again. _Maybe_ it is solved already, please let me know the results. If not, at least I know what pattern to look for in the code.

Thanks!

**Comment by lesslame** [comment]
Tried it and it worked nicely. Thanks again!!!
The result looks very good (but due to the size I cannot tell how complete it actually is). 
From my point of view this issue can be closed!

Just for documentation I will write down a few things that I saw in my log file:

The log-file showed the following errors. 
```powershell
[Error]: Failed to create groupv2-expiration-timer contact, skipping
[Error]: Asked to find recipient._id for empty e164. Refusing
[Error]: No results trying to get new recipient data.
``` 
The first error occurred 17 times, the "e164" two times and the "No results" only once.

This warning occurrs 17 times:
```powershell
[Warning]: Failed to find recipient for uuid
```
which is probably OK, but on the other hand this line:
```powershell
Creating new recipient for id [...]
```
occurred more than 400 times, apparently happening for all (?) my contacts. (When looking into the html I can see that many chat partners appear nicely with name, phone number and avatar.) 

For all of my 103 thread ids this line was in the log:
```powershell
Failed to find matching thread for conversation, creating. [...]
```

Other warnings were:
```powershell
[Warning]: Failed to get number of attachments in quoted message. Skipping
[Warning]: Unsupported message type 'message-request-response-event' WITH messageRequestResponseEvent='BLOCK. Skipping message
[Warning]: Unsupported message type 'message-request-response-event' WITH messageRequestResponseEvent='UNBLOCK. Skipping message
[Warning]: Profile data empty. Not updating group recipient.
[Warning]: Failed to update profile data.
[Warning]: Call table not found in database
```

Not sure if any of this is helpful in any way, and if not, just ignore it.

**Comment by bepaald** [comment]
Excellent, I'm glad that's fixed.

Most of this output seems perfectly fine. Specifically:
>on the other hand this line:
>`Creating new recipient for id [...]`
>occurred more than 400 times, apparently happening for all (?) my contacts.

That is exactly expected. The `--exportdesktophtml` option internally works by importing the desktop data into an empty, dummy Android backup file, and then running the normal `--exporthtml` on that. Because the dummy backup file starts out empty, all contacts need to be created.

The only one that stands out to me is 
```
[Error]: Failed to create groupv2-expiration-timer contact, skipping
```
That one is actually a result of my commit this morning, and is a bug. It should be fixed now. Maybe you want to run again, just to verify the original issue is still fixed, and that you don't see any errors reading either `Failed to create group-v2-expiration-timer contact (n), skipping` or `Failed to create group-v2-update contact (n), skipping`.

Thanks for reporting back!

**Comment by lesslame** [comment]
That also worked nicely:
- Original issue is still fixed!
- 17 occurrences of "Failed to create groupv2-expiration-timer contact, skipping" are gone, good!
- One of those 17 was replaced by 
`[Error]: Failed to create group-v2-update contact (1), skipping`

**Comment by bepaald** [comment]
Thanks again, that looks much better.

Was another error printed right before `[Error]: Failed to create group-v2-update contact (1), skipping`?  It's probably not one that is fixable, but I'm still curious.

**Comment by lesslame** [comment]
yes, there was, this shows some more context:
```powershell
Successfully created new recipient for group (id: 203).
Failed to find matching thread for conversation, creating. (id: __signal_group__v2__!25f1 [...] d4084b8, thread_id: 89)
 - Importing 280 messages into thread._id 89
[Warning]: Failed to find recipient for uuid: pni:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Creating new recipient for id: pni:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[Error]: No results trying to get new recipient data.
[Error]: Failed to create group-v2-update contact (1), skipping
Trying to match conversation (91/104) (type: private)
Failed to find matching thread for conversation, creating. (id: c2b49a4a- [...] 22e0, thread_id: 90)
 - Importing 44 messages into thread._id 90
```

**Comment by bepaald** [comment]
Thanks, that is interesting, I did not realize some messages would have a PNI as the source on the Desktop client. I have made an attempt to deal with this case, though I'm not sure if I was successful. This is a somewhat difficult one since I don't have similar data in any of my own databases. I did handcraft something, but I can't be sure about some details of an entry like this as it would naturally occur.

So, I hate to do this to you, but would you please update, and run again, and let me know the output of that same part of the process?

I also added some more warnings when an unsupported status-message is encountered, just so I can get a list of them to (slowly) work through. So you may see some new warnings in the output, but functionally nothing has changed (they were skipped silently before).

Thanks!

**Comment by lesslame** [comment]
Hi, 
the two errors are gone, instead a "Successfully...", here is the new excerpt from the same spot in the log-file:

```powershell
Successfully created new recipient for group (id: 203).
Failed to find matching thread for conversation, creating. (id: __signal_group__v2__!25f1 [...] 2d4084b8, thread_id: 89)
 - Importing 288 messages into thread._id 89
[Warning]: Failed to find recipient for uuid: PNI:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Creating new recipient for id: PNI:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Successfully updated identity-key for contact (230, PNI:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
Successfully created new recipient (id: 230).
Trying to match conversation (91/104) (type: private)
Failed to find matching thread for conversation, creating. (id: c2b49a4akk [...] 22e0, thread_id: 90)
 - Importing 44 messages into thread._id 90
``` 

Exactly as you expected I also noted several additional warnings like
`[Warning]: Unsupported message type 'group-v2-change:member-privilege'. Skipping... (this warning will be shown only once)`
due to the additional details that are now shown after "group-v2-change:..". 

So everything seems very well now, thanks! If you agree you are welcome to close this issue.

**Comment by bepaald** [comment]
>So everything seems very well now, thanks! If you agree you are welcome to close this issue.

Thanks for reporting back, this all looks good to me now as well.

I will be making some more code changes, now that I know that a message source can sometimes be identified by PNI. Functionally, the code path you are running into should stay the same, so I agree this issue can be closed. But I will try to deal with this case for other code paths as well. 

Thanks again!
