### ISSUE TITLE
Signal Backup Merge

### ISSUE THREAD

**Issue by castanley** [bepaald/signalbackup-tools#7]
I opened the signal bug for the corrupt backups and was able to get back up and running using your fix (thanks a ton!)

I was wondering if there was any progress on the backup merge capability? During the wait, I had to start fresh. I would like to merge these two backups :)

No worries if this isn't something that is a priority right now.

Also, do you have a link to donate? I super appreciate the tool you have developed (it has helped me understand how signal does backups)

Thanks!

**Comment by bepaald** [comment]
> I opened the signal bug for the corrupt backups and was able to get back up and running using your fix (thanks a ton!)

Excellent, I'm always happy to hear success stories!

> I was wondering if there was any progress on the backup merge capability? During the wait, I had to start fresh. I would like to merge these two backups :)
> 
> No worries if this isn't something that is a priority right now.

Well, good news! I have already implemented the merging feature a while ago! The only reason it is not documented in the README is because nobody has tested it (as far as I know). But the old version was tested (successfully, by two people) and this version is just a rewrite for the current database schema (and I did a little testing on some of my own backups of course), so I am pretty hopeful it will just work.

Instructions:
```
./signalbackup-tools [BACKUPFILE1] [PASSWORD1] --importthreads ALL --source [BACKUPFILE2] --sourcepassword [PASSWORD2] --output [NEW_BACKUP] --opassword [NEW_PASSWORD] 
```
Expect a _ton_ of output (I should fix that). A few notes:
- Please keep your original backups. The program will only open then in read-only mode, so that should be fine. But don't go deleting them or anything, you might need to restore from them if the program fails for some reason.
- Since the internal database schema changed, older and newer versions of backup files cannot be merged together. Either both files need to be databaseversion < 27, both need to be > 33, or both need to be in between. The databaseversion can be found by running `./signalbackup-tools [BACKUPFILE] [PASSWORD] --listthreads`.
- Just in case the database schema has changed in between the versions in your two backup files, you should probably import from the older into the newer file (so, the older file is the '--source'). If both files have the same version, it would be best to use the smallest file as source (just for speed).
- If you do not want to import all of the threads, you could replace 'ALL' in the above command with a comma-and-hyphen-separated list of threads (eg: 1,4,6-13,15). To find out which thread is which, again use `--listthreads` and use the '_id' column.

That's it. I really hope it just works immediately. Depending on how large your database is, it might be somewhat hard to tell, but try. The program also allows you to run arbitrary SQL queries on the database, so as a simple check, you could for example run `./signalbackup-tools [BACKUPFILE] [PASSWORD] --runsqlquery "SELECT COUNT(*) FROM sms"` to get the number of entries in the sms table, in both the input databases, and check that the output database has the sum of that number. And the same for the 'mms' table. If, after inspection, you are unsure of the merger for some reason, I can probably come up with some other queries that would make it more or less likely the merge was a success.

If for some reason it does not work, I'd be happy to work with you to try and fix it. But it will require a bit of patience and a willingness to run test-versions and answer my annoying questions :)

> Also, do you have a link to donate? I super appreciate the tool you have developed (it has helped me understand how signal does backups)

There are donation links at the bottom of the README file (on the mainpage here: https://github.com/bepaald/signalbackup-tools). Please do not feel obligated in any way, I'll do my best to help regardless. Having said that, if you feel you want to donate (and you can afford to), I really do appreciate it a lot!

Thanks!

**Comment by Esokrates** [comment]
@bepaald I am back again for testing. I want to merge my backups now with merging threads as I did not do that last time and therefore have no used the merge backup because of too much clutter. I still have the old Signal version installed. What should I do now? Should I compile current master and try it with that or should I stick to an old version and if so at which commit?

**Comment by bepaald** [comment]
@Esokrates: yes, all the changes to the 'importthreads' code should be backwards compatible. The code to merge recipients and edit group members was never updated, so that should still work on the old databases (and not at all on the new ones).

So, it should be safe to get the current master, and then merge the backups as you did before. Then, run `signalbackup-tools --mergerecipients recipient_id1,recipient_id2,...,recipient_idN --editgroupmembers --output [OUTPUT] --opassword [NEWPASSWORD] [MERGED] [MERGEDPASSWORD]`, where recipients_id1 - recipient_id(N-1) are all the old numbers you want to change into recipient_idN (which would be the new, current number). You would need to repeat this step for each set of recipient_ids you want to merge into one.

> I want to merge my backups now with merging threads

I assume you mean 'merging _recipients_'? Threads with the same recipient_id are always merged by the normal 'importthreads' option. Threads with different recipient_id's are never merged (even if they are groups with the same memberlist), though if you need this option, I could probably implement it.

**Comment by Esokrates** [comment]
@bepaald Tested the  `--mergerecipients` now to merge a contact who changed number into his newer number.  That worked well, however there is a bug: In the part from the old recipient referenced messages still show the old contact name and clicking on the reference does not work (tells me that the original message is not available anymore although it is available). Would be glad if you could fix that!

**Comment by bepaald** [comment]
@Esokrates Right, I forgot about quotes! I think I fixed it, try it now...

**Comment by Esokrates** [comment]
I tested it, did not work unfortunately (I pulled and simply rerun the build script, should I've cleaned something?)

**Comment by bepaald** [comment]
Hm, that's odd, though I did not test it very thouroughly. Could you confirm this for loop is in your sources: https://github.com/bepaald/signalbackup-tools/blob/master/signalbackup/mergerecipients.cc#L63 That for-loop was supposed to change the quote authors. In the output, can you see any lines reading _'Updated (number) quotes in 'mms' table'_?

If not, I'll have to do some testing, but I'll have to do that tomorrow at the earliest.

**Comment by bepaald** [comment]
@Esokrates Sorry, found a stupid mistake in my sql query. It was just one line, and I still f'ed it, haha. One comma that didn't belong there. Please try it again!

**Comment by Esokrates** [comment]
@bepaald Thanks very much, now it works :-). I noticed another more critical issue: I was running out of disk space, my backup file had 880MB and I had only 770MB of remaining space: The process completed without showing any errors, but the output file was only 770MB, so there was clearly something missing!
When clearing disk space and rerunning the process the output file had the expected 880MB. Could you maybe implement some checks that check if the output file is indeed complete and if not throwing an error at the end?

**Comment by Esokrates** [comment]
@bepaald Could you make it possible to merge different groups into one?

**Comment by bepaald** [comment]
@Esokrates 
> Could you maybe implement some checks that check if the output file is indeed complete and if not throwing an error at the end?

done

> Could you make it possible to merge different groups into one?

and done.

Well, a first attempt anyway. Syntax is pretty much the same as the mergerecipients option, you use what is listed under 'recipient_ids' when calling `--listthreads`. Note: the exclamation mark (!) is a special character in bash shells, you need to escape it with a backslash (\\). Example:
```
./signalbackup-tools [input] [inputpassword] --mergegroups __textsecure_group__\!8f5626480b19404c9e3028b77b7cee37,__textsecure_group__\!afbeccd7f039a3ef423b1015527415f5 -o [output] -op [outputpassword]
```
Again, all groups listed  _before_ the last one are merged into the last one on the list. Repeat as necessary. It actually does merge the memberlists (skipping doubles), but does not deal with the memberlist change-messages (that is very difficult I think). But in the case you describe it wouldn't matter anyway.

Let me know if it works, it was only poorly tested.

**Comment by Esokrates** [comment]
Merging groups seemed to have worked just fine, also I can confirm the tool to throw an error now when the database can't be written.

1. When running `mergerecipients` or `mergegroups` for the old backup file I get:
    ```
    Dealing with table 'part'... 592/1040 entries...Warning: attachment data not found (rowid: 602, uniqueid: 1472167059569)
    Dealing with table 'part'... 593/1040 entries...Warning: attachment data not found (rowid: 603, uniqueid: 1472167059885)
    Dealing with table 'part'... 594/1040 entries...Warning: attachment data not found (rowid: 604, uniqueid: 1472167060310)
    Dealing with table 'part'... 595/1040 entries...Warning: attachment data not found (rowid: 605, uniqueid: 1472167061149)
    Dealing with table 'part'... 596/1040 entries...Warning: attachment data not found (rowid: 606, uniqueid: 1472167061458)
    Dealing with table 'part'... 598/1040 entries...Warning: attachment data not found (rowid: 608, uniqueid: 1472167062803)
    Dealing with table 'part'... 599/1040 entries...Warning: attachment data not found (rowid: 609, uniqueid: 1472167063153)
    Dealing with table 'part'... 600/1040 entries...Warning: attachment data not found (rowid: 610, uniqueid: 1472167063337)
    ```
    What is the reason for this? Could you tell me what to do to fix this?
2. The merged group's memberlist is a union of the memberlists of the individual groups. I noticed that Signal does not allow me to remove group members. In my case I have all the ghost numbers in my unified group and I can't get rid of them (`mergerecipients does not alter group membership`). Could you allow me to get rid of those? I see 3 possibilities:
    - allow `mergerecipients` to alter groups memberships with an additional option
    - do not alter the memberlist of the group the other groups are merged into optionally with an additional option
    - introduce an option to delete members from a specified group

   I guess the third option is the cleanest but you're the expert. 

3. Merging two backups with `--importthreads ALL` did not work as expected: the output file was smaller than the bigger of the two files. When looking at the output it was apparent that it tried to import nonexisting threads  and while doing so printed `Failed to get recipient id from source database` but left out some existent threads (e.g. it tried to import thread 1 which is not listed, but left out thread 15, some threads were correctly imported though).

   Manually specifing the threads to import worked well though.

**Comment by bepaald** [comment]
@Esokrates 
>When running mergerecipients or mergegroups for the old backup file I get:
What is the reason for this? Could you tell me what to do to fix this?

This is something with your backup file, it means there are entries in the part table of the database without any corresponding AttachmentFrames. I don't know exactly what leads to this, but it is quite a normal situation and usually harmless. I would however expect it to give the same output even without the `merge`-options. I expect the same output from just `./signalbackup-tools [input] [password] -o [output] -op [password]` (with the same password should really just be a copy of the original file). Do you see it in this case, or does that only happen when using a `merge`-option?

>The merged group's memberlist is a union of the memberlists of the individual groups. I noticed that Signal does not allow me to remove group members. In my case I have all the ghost numbers in my unified group and I can't get rid of them (mergerecipients does not alter group membership`). Could you allow me to get rid of those? I see 3 possibilities:
allow mergerecipients to alter groups memberships with an additional option

It should do this. As I posted earlier, and mentioned in this thread there already is an additional option to `mergerecipients` to also edit group members (`editgroupmembers`), see: https://github.com/bepaald/signalbackup-tools/issues/4#issuecomment-544991847 or https://github.com/bepaald/signalbackup-tools/issues/7#issuecomment-562166998 Did you miss this, or did you try this but it doesn't work?

>Merging two backups with --importthreads ALL did not work as expected

Thanks! I've fixed it now (hopefully).

**Comment by Esokrates** [comment]
### Feedback
> This is something with your backup file, it means there are entries in the part table of the database without any corresponding AttachmentFrames. I don't know exactly what leads to this, but it is quite a normal situation and usually harmless. I would however expect it to give the same output even without the merge-options. I expect the same output from just ./signalbackup-tools [input] [password] -o [output] -op [password] (with the same password should really just be a copy of the original file). Do you see it in this case, or does that only happen when using a merge-option?

As noted in https://github.com/bepaald/signalbackup-tools/issues/4#issuecomment-564236556 the warnings all come down to the NULL errors creating the crash, as discussed in the other thread, I'll continue the discussion about that specific problem there.

> It should do this. As I posted earlier, and mentioned in this thread there already is an additional option to mergerecipients to also edit group members (editgroupmembers), see: #4 (comment) or #7 (comment) Did you miss this, or did you try this but it doesn't work?

I totally missed the `editgroupmembers` option! I tried it now and it works perfectly!

> Thanks! I've fixed it now (hopefully).

Tested, `--importthreads ALL` works as expected now :-).

### Feature Request
Back in the day when Signal had no proper backup functionality and it only exported text I accidentally imported a text backup which lead to all messages being duplicated at the time.
Now I scrolled back to that period and noticed all those messages are marked as unencrypted sms messages. I would like to deduplicate my conversation, could you help me make that happen?
The duplicate message should be easy to match:
- they have exactly the same timestamp and text as the original message
- they show as unencrypted sms messages.

**Comment by bepaald** [comment]
> I'll continue the discussion about that specific problem there

Yes, in fact, let's please move all discussion to that thread. Having two different conversations with the same person simultaneously is confusing me :-)

**Comment by bepaald** [comment]
@castanley Sorry for all the noise on this thread, most of it was not very relevant to your case. However, Esokrates did find a bug in my `--importthreads ALL` function, so in case you already tried the merge and had some problems, please try again!

**Comment by tadu** [comment]
Unfortunately, it seems merging does not create valid backups - or breaks them. Depending on the order of merge, Signal either immediately FC, or message threads are associated with random contacts. :/

**Comment by bepaald** [comment]
@tadu Ok, I found some problems indeed that may have caused your problems. All leftover issues from Signal's big recipient_id database switchover. I spent most of the day yesterday trying to fix them, now running tests and making sure the old versions also still work ok. It might be a couple more days before I push, but I'll let you know and you might want to try again.

Thanks!

**Comment by bepaald** [comment]
@tadu I just pushed some changes which will hopefully fix the issues with merging. I hope it works and you will want to try again. If you do, please let me know the results! Thanks!

**Comment by tadu** [comment]
Except that the newest version throws lots of warnings regarding unknown attributes ([[likely]] and [[unlikely]] is C++20, but not supported yet by e.g. clang++-9), it does the job and merged the backups correctly as far as I can see (chats assigned to correct contacts - didn't check all messages, but presumably correct). Thanks for your fix!

**Comment by bepaald** [comment]
No problem!

@all: I think I will actually close this issue now, as everything seems to either be solved (or abandoned?). If anyone wants to continue any discussion that started here, just feel free to keep posting here or open a new issue.

**Comment by thornySoap** [comment]
> Instructions:
> 
> ./signalbackup-tools [BACKUPFILE1] [PASSWORD1] --importthreads ALL --source [BACKUPFILE2] --sourcepassword [PASSWORD2] --output [NEW_BACKUP] --opassword [NEW_PASSWORD] 
> 

@bepaald Hello! Thank you for your work. I am trying to merge two backups with database versions 281 and 283 and it seemingly suceeds, aside from chats in the same "chat folder" being separated into different folders with the same name. But after a while, Signal suddenly crashes and it does so immediately again after reopening it.

This is the stack trace:  
```
org.thoughtcrime.securesms.storage.StorageSyncValidations$DuplicateStorageIdError
        at org.thoughtcrime.securesms.storage.StorageSyncValidations.validateManifestAndInserts(StorageSyncValidations.java:125)
        at org.thoughtcrime.securesms.storage.StorageSyncValidations.validate(StorageSyncValidations.java:36)
        at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.kt:398)
        at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.kt:208)
        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:88)
        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:51)
```

I'm using version `signalbackup-tools (./signalbackup-tools) source version 20250701.165013 (SQLite: 3.37.2, OpenSSL: OpenSSL 3.0.2 15 Mar 2022)` extracted from the Debian/Ubuntu ppa `.deb`.

**Comment by bepaald** [comment]
Thanks for the report @thornySoap! I've made a separate issue for this (#332), I'll look into this.
